// src/constants/reviewPlatforms.js
// Map platform display names to their primary domains and brand colors (approximate)

export const REVIEW_PLATFORMS = {
  Google: { domain: 'google.com', color: '#4285F4' },
  Facebook: { domain: 'facebook.com', color: '#1877F2' },
  Trustpilot: { domain: 'trustpilot.com', color: '#00B67A' },
  Yelp: { domain: 'yelp.com', color: '#D32323' },
  'Yellow Pages': { domain: 'yellowpages.com', color: '#FFCC00' },
  TripAdvisor: { domain: 'tripadvisor.com', color: '#34E0A1' },
  Yell: { domain: 'yell.com', color: '#FFD100' },
  Zillow: { domain: 'zillow.com', color: '#006AFF' },
  'Better Business Bureau': { domain: 'bbb.org', color: '#168CCC' },
  HomeAdvisor: { domain: 'homeadvisor.com', color: '#F28C00' },
  Houzz: { domain: 'houzz.com', color: '#4DBC15' },
  Amazon: { domain: 'amazon.com', color: '#FF9900' },
  'Booking.com': { domain: 'booking.com', color: '#003580' },
  'Angies List': { domain: 'angi.com', color: '#D40000' },
  'Service Seeking': { domain: 'serviceseeking.com.au', color: '#00B3E6' },
  'Apple App Store': { domain: 'apple.com', color: '#000000' },
  'Apple Podcasts': { domain: 'podcasts.apple.com', color: '#A050E0' },
  TrustATrader: { domain: 'trustatrader.com', color: '#003A6C' },
  Airbnb: { domain: 'airbnb.com', color: '#FF5A5F' },
  'Hotels.com': { domain: 'hotels.com', color: '#D32F2F' },
  G2: { domain: 'g2.com', color: '#FF492C' },
  Capterra: { domain: 'capterra.com', color: '#1F73B7' },
  OpenTable: { domain: 'opentable.com', color: '#D73530' },
  Edmunds: { domain: 'edmunds.com', color: '#0076CE' },
  Checkatrade: { domain: 'checkatrade.com', color: '#00AEEF' },
  Vitals: { domain: 'vitals.com', color: '#5B7C99' },
  WebMD: { domain: 'webmd.com', color: '#2B6CB0' },
  'Just Eat': { domain: 'just-eat.co.uk', color: '#F36C2B' },
  MyBuilder: { domain: 'mybuilder.com', color: '#0071B3' },
  VRBO: { domain: 'vrbo.com', color: '#0A85EA' },
  Mindbody: { domain: 'mindbodyonline.com', color: '#FF6F61' },
  'Legelisten.no': { domain: 'legelisten.no', color: '#2E5AAC' },
  Deliveroo: { domain: 'deliveroo.co.uk', color: '#00C1B2' },
  'Takeaway.com': { domain: 'takeaway.com', color: '#FF8000' },
  Agoda: { domain: 'agoda.com', color: '#5458F7' },
  GetAgent: { domain: 'getagent.co.uk', color: '#0B5FFF' },
  Zomato: { domain: 'zomato.com', color: '#E23744' },
  Doctify: { domain: 'doctify.com', color: '#0FA3B1' },
  Healthgrades: { domain: 'healthgrades.com', color: '#0066FF' },
  RateMDs: { domain: 'ratemds.com', color: '#00A3A3' },
  Booksy: { domain: 'booksy.com', color: '#000000' },
  PatientConnect365: { domain: 'patientconnect365.com', color: '#1C7ED6' },
  RealSelf: { domain: 'realself.com', color: '#00B3A4' },
  Thuisbezorgd: { domain: 'thuisbezorgd.nl', color: '#FF8000' },
  Rover: { domain: 'rover.com', color: '#00BF6F' },
  RepairPal: { domain: 'repairpal.com', color: '#0077B6' },
  Anwalt: { domain: 'anwalt.de', color: '#1D5F8A' },
  Advocado: { domain: 'advocado.de', color: '#00A5A5' },
  Kununu: { domain: 'kununu.com', color: '#00ADEF' },
}

export const getPlatformInfo = (name) => REVIEW_PLATFORMS[name] || null;
